/* Generated By:JavaCC: Do not edit this line. NewickParserConstants.java */
package conifer.io.newick;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NewickParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER_STRING = 5;
  /** RegularExpression Id. */
  int NODE_NAME_STRING = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<NUMBER_STRING>",
    "<NODE_NAME_STRING>",
    "\";\"",
    "\":\"",
    "\"(\"",
    "\",\"",
    "\")\"",
  };

}
